spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        format_sql: true
        hbm2ddl:
          auto: none

  datasource:
    url: jdbc:postgresql://localhost:5433/basketball
    username: postgres
    password: p0stgr3s
    driverClassName: org.postgresql.Driver
    hikari:
      maximum-pool-size: 2
      connection-timeout: 5000
