CREATE SEQUENCE SEQ_EQUIPE START WITH 1 INCREMENT BY 1;

CREATE TABLE EQUIPE
(
    ID        INTEGER,
    NOME      VARCHAR(255) NOT NULL,
    FK_CIDADE INTEGER      NOT NULL,

    CONSTRAINT PK_EQUIPE PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_JOGADOR START WITH 1 INCREMENT BY 1;

CREATE TABLE JOGADOR
(
    ID        INTEGER,
    NOME      VARCHAR(255) NOT NULL,
    FK_EQUIPE INTEGER,

    CONSTRAINT PK_JOGADOR PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_CIDADE START WITH 1 INCREMENT BY 1;

CREATE TABLE CIDADE
(
    ID   INTEGER,
    UF   VARCHAR(2)   NOT NULL,
    NOME VARCHAR(255) NOT NULL,

    CONSTRAINT PK_CIDADE PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_TECNICO START WITH 1 INCREMENT BY 1;

CREATE TABLE TECNICO
(
    ID        INTEGER,
    NOME      VARCHAR(255) NOT NULL,
    FUNCAO    VARCHAR(255) NOT NULL,
    FK_EQUIPE INTEGER,

    CONSTRAINT PK_TECNICO PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_JOGO START WITH 1 INCREMENT BY 1;

CREATE TABLE JOGO
(
    ID                  INTEGER,
    FK_EQUIPE_CASA      INTEGER   NOT NULL,
    FK_EQUIPE_VISITANTE INTEGER   NOT NULL,
    PONTOS_CASA         INTEGER   NOT NULL,
    PONTOS_VISITANTE    INTEGER   NOT NULL,
    DATA                TIMESTAMP NOT NULL,

    CONSTRAINT PK_JOGO PRIMARY KEY (ID)
);

ALTER TABLE EQUIPE
    ADD CONSTRAINT FK_EQUIPE_CIDADE FOREIGN KEY (FK_CIDADE) REFERENCES CIDADE (ID);

ALTER TABLE JOGADOR
    ADD CONSTRAINT FK_JOGADOR_EQUIPE FOREIGN KEY (FK_EQUIPE) REFERENCES EQUIPE (ID);

ALTER TABLE TECNICO
    ADD CONSTRAINT FK_TECNICO_EQUIPE FOREIGN KEY (FK_EQUIPE) REFERENCES EQUIPE (ID);

ALTER TABLE JOGO
    ADD CONSTRAINT FK_JOGO_EQUIPE_CASA FOREIGN KEY (FK_EQUIPE_CASA) REFERENCES EQUIPE (ID);

ALTER TABLE JOGO
    ADD CONSTRAINT FK_JOGO_EQUIPE_VISITANTE FOREIGN KEY (FK_EQUIPE_VISITANTE) REFERENCES EQUIPE (ID);
