INSERT INTO CIDADE (ID, UF, NOME)
VALUES (NEXTVAL('SEQ_CIDADE'), 'SP', 'Adamantina'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Adolfo'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Agisse'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Agua Vermelha'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Aguai'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Aguas da Prata'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Aguas de Lindoia'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Aguas de Santa Barbara'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Aguas de Sao Pedro'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Agudos'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Agulha'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Ajapi'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Alambari'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Alberto Moreira'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Aldeia'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Aldeia de Carapicuiba'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Alfredo Guedes'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Alfredo Marcondes'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Altair'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Altinopolis'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Alto Alegre'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Alto Pora'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Aluminio'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Alvares Florence'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Alvares Machado'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Alvaro de Carvalho'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Alvinlandia'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Amadeu Amaral'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Amandaba'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Ameliopolis'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Americana'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Americo Brasiliense'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Americo de Campos'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Amparo'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Ana Dias'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Analandia'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Anapolis'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Andes'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Andradina'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Angatuba'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Anhembi'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Anhumas'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Aparecida'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Aparecida D''oeste'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Aparecida de Monte Alto'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Aparecida de Sao Manuel'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Aparecida do Bonito'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Apiai'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Apiai-mirim'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Arabela'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Aracacu'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Aracaiba'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Aracariguama'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Aracatuba'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Aracoiaba da Serra'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Aramina'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Arandu'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Arapei'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Araraquara'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Araras'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Araxas'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Arcadas'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Arco-iris'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Arealva'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Areias'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Areiopolis'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Ariranha'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Ariri'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Artemis'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Artur Nogueira'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Aruja'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Aspasia'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Assis'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Assistencia'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Atibaia'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Atlantida'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Auriflama'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Avai'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Avanhandava'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Avare'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Avencas'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Bacaetava'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Bacuriti'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Bady Bassitt'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Baguacu'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Bairro Alto'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Balbinos'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Balsamo'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Bananal'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Bandeirantes D''oeste'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Barao Ataliba Nogueira'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Barao de Antonina'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Barao de Geraldo'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Barbosa'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Bariri'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Barra Bonita'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Barra do Chapeu'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Barra do Turvo'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Barra Dourada'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Barrania'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Barretos'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Barrinha'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Barueri'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Bastos'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Batatais'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Batatuba'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Batista Botelho'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Bauru'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Bebedouro'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Bela Floresta'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Bela Vista Sao-carlense'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Bento de Abreu'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Bernardino de Campos'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Bertioga'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Bilac'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Birigui'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Biritiba-mirim'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Biritiba-ussu'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Boa Esperanca do Sul'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Boa Vista dos Andradas'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Boa Vista Paulista'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Bocaina'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Bofete'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Boituva'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Bom Fim do Bom Jesus'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Bom Jesus dos Perdoes'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Bom Retiro da Esperanca'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Bom Sucesso de Itarare'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Bonfim Paulista'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Bora'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Boraceia'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Borborema'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Borebi'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Botafogo'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Botelho'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Botucatu'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Botujuru'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Braco'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Braganca Paulista'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Bras Cubas'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Brasitania'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Brauna'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Brejo Alegre'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Brodowski'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Brotas'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Bueno de Andrada'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Buri'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Buritama'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Buritizal'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Cabralia Paulista'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Cabreuva'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Cacapava'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Cachoeira de Emas'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Cachoeira Paulista'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Caconde'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Cafelandia'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Cafesopolis'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Caiabu'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Caibura'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Caieiras'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Caiua'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Cajamar'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Cajati'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Cajobi'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Cajuru'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Cambaquara'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Cambaratiba'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Campestrinho'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Campina de Fora'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Campina do Monte Alegre'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Campinal'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Campinas'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Campo Limpo Paulista'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Campos de Cunha'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Campos do Jordao'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Campos Novos Paulista'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Cananeia'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Canas'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Candia'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Candido Mota'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Candido Rodrigues'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Canguera'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Canitar'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Capao Bonito'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Capela do Alto'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Capivari'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Capivari da Mata'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Caporanga'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Capuava'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Caraguatatuba'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Carapicuiba'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Cardeal'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Cardoso'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Caruara'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Casa Branca'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Cassia dos Coqueiros'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Castilho'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Catanduva'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Catigua'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Catucaba'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Caucaia do Alto'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Cedral'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Cerqueira Cesar'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Cerquilho'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Cesario Lange'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Cezar de Souza'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Charqueada'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Chavantes'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Cipo-guacu'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Clarinia'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Clementina'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Cocaes'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Colina'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Colombia'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Conceicao de Monte Alegre'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Conchal'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Conchas'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Cordeiropolis'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Coroados'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Coronel Goulart'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Coronel Macedo'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Corredeira'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Corrego Rico'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Corumbatai'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Cosmopolis'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Cosmorama'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Costa Machado'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Cotia'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Cravinhos'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Cristais Paulista'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Cruz das Posses'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Cruzalia'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Cruzeiro'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Cubatao'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Cuiaba Paulista'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Cunha'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Curupa'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Dalas'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Descalvado'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Diadema'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Dirce Reis'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Dirceu'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Divinolandia'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Dobrada'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Dois Corregos'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Dolcinopolis'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Domelia'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Dourado'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Dracena'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Duartina'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Dumont'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Duplo Ceu'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Echapora'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Eldorado'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Eleuterio'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Elias Fausto'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Elisiario'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Embauba'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Embu'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Embu-guacu'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Emilianopolis'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Eneida'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Engenheiro Balduino'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Engenheiro Coelho'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Engenheiro Maia'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Engenheiro Schmidt'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Esmeralda'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Esperanca D''oeste'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Espigao'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Espirito Santo do Pinhal'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Espirito Santo do Turvo'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Estiva Gerbi'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Estrela D''oeste'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Estrela do Norte'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Euclides da Cunha Paulista'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Eugenio de Melo'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Fartura'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Fatima'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Fatima Paulista'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Fazenda Velha'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Fernando Prestes'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Fernandopolis'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Fernao'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Ferraz de Vasconcelos'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Flora Rica'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Floreal'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Floresta do Sul'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Florida Paulista'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Florinea'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Franca'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Francisco Morato'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Franco da Rocha'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Frutal do Campo'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Gabriel Monteiro'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Galia'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Garca'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Gardenia'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Gastao Vidigal'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Gaviao Peixoto'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'General Salgado'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Getulina'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Glicerio'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Gramadinho'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Guachos'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Guaianas'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Guaicara'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Guaimbe'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Guaira'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Guamium'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Guapiacu'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Guapiara'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Guapiranga'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Guara'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Guaracai'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Guaraci'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Guaraciaba D''oeste'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Guarani D''oeste'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Guaranta'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Guarapiranga'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Guarapua'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Guararapes'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Guararema'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Guaratingueta'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Guarei'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Guariba'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Guariroba'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Guarizinho'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Guaruja'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Guarulhos'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Guatapara'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Guzolandia'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Herculandia'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Holambra'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Holambra Ii'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Hortolandia'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Iacanga'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Iacri'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Iaras'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Ibate'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Ibiporanga'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Ibira'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Ibirarema'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Ibitinga'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Ibitiruna'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Ibitiuva'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Ibitu'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Ibiuna'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Icem'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Ida Iolanda'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Iepe'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Igacaba'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Igaracu do Tiete'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Igarai'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Igarapava'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Igarata'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Iguape'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Ilha Comprida'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Ilha Diana'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Ilha Solteira'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Ilhabela'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Indaia do Aguapei'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Indaiatuba'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Indiana'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Indiapora'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Ingas'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Inubia Paulista'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Ipaussu'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Ipero'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Ipeuna'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Ipigua'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Iporanga'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Ipua'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Iracemapolis'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Irape'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Irapua'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Irapuru'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Itabera'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Itaboa'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Itai'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Itaiuba'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Itajobi'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Itaju'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Itanhaem'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Itaoca'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Itapecerica da Serra'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Itapetininga'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Itapeuna'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Itapeva'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Itapevi'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Itapira'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Itapirapua Paulista'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Itapolis'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Itaporanga'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Itapui'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Itapura'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Itaquaquecetuba'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Itaqueri da Serra'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Itarare'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Itariri'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Itatiba'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Itatinga'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Itirapina'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Itirapua'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Itobi'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Itororo do Paranapanema'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Itu'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Itupeva'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Ituverava'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Iubatinga'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Jaborandi'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Jaboticabal'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Jacare'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Jacarei'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Jaci'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Jacipora'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Jacuba'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Jacupiranga'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Jafa'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Jaguariuna'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Jales'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Jamaica'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Jambeiro'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Jandira'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Jardim Belval'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Jardim Presidente Dutra'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Jardim Santa Luzia'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Jardim Silveira'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Jardinopolis'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Jarinu'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Jatoba'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Jau'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Jeriquara'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Joanopolis'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Joao Ramalho'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Joaquim Egidio'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Jordanesia'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Jose Bonifacio'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Juliania'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Julio Mesquita'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Jumirim'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Jundiai'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Jundiapeba'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Junqueira'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Junqueiropolis'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Juquia'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Juquiratiba'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Juquitiba'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Juritis'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Juruce'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Jurupeba'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Jurupema'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Lacio'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Lagoa Azul'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Lagoa Branca'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Lagoinha'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Laranjal Paulista'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Laras'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Lauro Penteado'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Lavinia'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Lavrinhas'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Leme'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Lencois Paulista'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Limeira'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Lindoia'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Lins'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Lobo'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Lorena'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Lourdes'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Louveira'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Lucelia'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Lucianopolis'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Luis Antonio'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Luiziania'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Lupercio'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Lusitania'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Lutecia'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Macatuba'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Macaubal'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Macedonia'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Macucos'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Magda'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Mailasqui'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Mairinque'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Mairipora'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Major Prado'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Manduri'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Mangaratu'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Maraba Paulista'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Maracai'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Marapoama'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Marcondesia'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Maresias'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Mariapolis'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Marilia'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Marinopolis'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Maristela'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Martim Francisco'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Martinho Prado Junior'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Martinopolis'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Matao'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Maua'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Mendonca'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Meridiano'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Mesopolis'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Miguelopolis'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Mineiros do Tiete'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Mira Estrela'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Miracatu'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Miraluz'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Mirandopolis'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Mirante do Paranapanema'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Mirassol'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Mirassolandia'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Mococa'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Mogi das Cruzes'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Mogi-guacu'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Mogi-mirim'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Mombuca'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Moncoes'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Mongagua'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Montalvao'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Monte Alegre do Sul'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Monte Alto'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Monte Aprazivel'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Monte Azul Paulista'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Monte Cabrao'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Monte Castelo'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Monte Mor'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Monte Verde Paulista'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Monteiro Lobato'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Moreira Cesar'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Morro Agudo'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Morro do Alto'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Morungaba'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Mostardas'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Motuca'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Mourao'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Murutinga do Sul'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Nantes'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Narandiba'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Natividade da Serra'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Nazare Paulista'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Neves Paulista'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Nhandeara'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Nipoa'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Nogueira'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Nossa Senhora do Remedio'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Nova Alexandria'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Nova Alianca'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Nova America'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Nova Aparecida'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Nova Campina'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Nova Canaa Paulista'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Nova Castilho'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Nova Europa'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Nova Granada'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Nova Guataporanga'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Nova Independencia'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Nova Itapirema'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Nova Luzitania'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Nova Odessa'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Nova Patria'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Nova Veneza'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Novais'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Novo Cravinhos'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Novo Horizonte'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Nuporanga'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Oasis'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Ocaucu'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Oleo'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Olimpia'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Oliveira Barros'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Onda Branca'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Onda Verde'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Oriente'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Orindiuva'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Orlandia'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Osasco'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Oscar Bressane'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Osvaldo Cruz'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Ourinhos'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Ouro Fino Paulista'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Ouro Verde'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Ouroeste'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Pacaembu'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Padre Nobrega'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Palestina'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Palmares Paulista'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Palmeira D''oeste'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Palmeiras de Sao Paulo'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Palmital'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Panorama'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Paraguacu Paulista'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Paraibuna'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Paraiso'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Paraisolandia'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Paranabi'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Paranapanema'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Paranapiacaba'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Paranapua'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Parapua'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Pardinho'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Pariquera-acu'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Parisi'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Parnaso'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Parque Meia Lua'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Paruru'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Patrocinio Paulista'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Pauliceia'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Paulinia'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Paulistania'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Paulo de Faria'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Paulopolis'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Pederneiras'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Pedra Bela'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Pedra Branca de Itarare'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Pedranopolis'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Pedregulho'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Pedreira'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Pedrinhas Paulista'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Pedro Barros'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Pedro de Toledo'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Penapolis'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Pereira Barreto'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Pereiras'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Peruibe'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Piacatu'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Picinguaba'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Piedade'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Pilar do Sul'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Pindamonhangaba'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Pindorama'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Pinhalzinho'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Pinheiros'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Pioneiros'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Piquerobi'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Piquete'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Piracaia'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Piracicaba'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Piraju'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Pirajui'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Piramboia'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Pirangi'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Pirapitingui'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Pirapora do Bom Jesus'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Pirapozinho'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Pirassununga'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Piratininga'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Pitangueiras'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Planalto'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Planalto do Sul'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Platina'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Poa'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Poloni'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Polvilho'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Pompeia'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Pongai'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Pontal'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Pontalinda'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Pontes Gestal'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Populina'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Porangaba'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Porto Feliz'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Porto Ferreira'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Porto Novo'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Potim'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Potirendaba'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Potunduva'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Pracinha'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Pradinia'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Pradopolis'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Praia Grande'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Pratania'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Presidente Alves'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Presidente Bernardes'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Presidente Epitacio'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Presidente Prudente'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Presidente Venceslau'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Primavera'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Promissao'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Prudencio E Moraes'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Quadra'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Quata'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Queiroz'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Queluz'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Quintana'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Quiririm'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Rafard'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Rancharia'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Rechan'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Redencao da Serra'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Regente Feijo'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Reginopolis'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Registro'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Restinga'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Riacho Grande'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Ribeira'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Ribeirao Bonito'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Ribeirao Branco'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Ribeirao Corrente'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Ribeirao do Sul'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Ribeirao dos Indios'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Ribeirao Grande'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Ribeirao Pires'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Ribeirao Preto'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Ribeiro do Vale'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Ribeiro dos Santos'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Rifaina'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Rincao'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Rinopolis'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Rio Claro'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Rio das Pedras'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Rio Grande da Serra'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Riolandia'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Riversul'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Roberto'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Rosalia'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Rosana'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Roseira'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Rubiacea'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Rubiao Junior'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Rubineia'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Ruilandia'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Sabauna'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Sabino'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Sagres'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Sales'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Sales Oliveira'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Salesopolis'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Salmourao'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Saltinho'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Salto'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Salto de Pirapora'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Salto do Avanhandava'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Salto Grande'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Sandovalina'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Santa Adelia'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Santa Albertina'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Santa America'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Santa Barbara D''oeste'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Santa Branca'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Santa Clara D''oeste'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Santa Cruz da Conceicao'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Santa Cruz da Esperanca'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Santa Cruz da Estrela'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Santa Cruz das Palmeiras'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Santa Cruz do Rio Pardo'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Santa Cruz dos Lopes'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Santa Ernestina'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Santa Eudoxia'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Santa Fe do Sul'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Santa Gertrudes'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Santa Isabel'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Santa Isabel do Marinheiro'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Santa Lucia'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Santa Margarida Paulista'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Santa Maria da Serra'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Santa Maria do Gurupa'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Santa Mercedes'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Santa Rita D''oeste'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Santa Rita do Passa Quatro'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Santa Rita do Ribeira'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Santa Rosa de Viterbo'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Santa Salete'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Santa Teresinha de Piracicaba'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Santana da Ponte Pensa'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Santana de Parnaiba'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Santelmo'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Santo Anastacio'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Santo Andre'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Santo Antonio da Alegria'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Santo Antonio da Estiva'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Santo Antonio de Posse'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Santo Antonio do Aracangua'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Santo Antonio do Jardim'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Santo Antonio do Paranapanema'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Santo Antonio do Pinhal'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Santo Antonio Paulista'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Santo Expedito'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Santopolis do Aguapei'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Santos'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Sao Benedito da Cachoeirinha'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Sao Benedito das Areias'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Sao Bento do Sapucai'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Sao Bernardo do Campo'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Sao Berto'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Sao Caetano do Sul'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Sao Carlos'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Sao Francisco'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Sao Francisco da Praia'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Sao Francisco Xavier'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Sao Joao da Boa Vista'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Sao Joao das Duas Pontes'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Sao Joao de Iracema'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Sao Joao de Itaguacu'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Sao Joao do Marinheiro'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Sao Joao Do Pau D''alho'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Sao Joao Novo'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Sao Joaquim da Barra'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Sao Jose da Bela Vista'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Sao Jose das Laranjeiras'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Sao Jose do Barreiro'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Sao Jose do Rio Pardo'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Sao Jose do Rio Preto'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Sao Jose dos Campos'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Sao Lourenco da Serra'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Sao Lourenco do Turvo'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Sao Luis do Paraitinga'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Sao Luiz do Guaricanga'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Sao Manuel'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Sao Martinho D''oeste'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Sao Miguel Arcanjo'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Sao Paulo'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Sao Pedro'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Sao Pedro do Turvo'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Sao Roque'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Sao Roque da Fartura'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Sao Sebastiao'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Sao Sebastiao da Grama'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Sao Sebastiao da Serra'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Sao Silvestre de Jacarei'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Sao Simao'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Sao Vicente'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Sapezal'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Sarapui'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Sarutaia'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Sebastianopolis do Sul'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Serra Azul'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Serra Negra'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Serrana'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Sertaozinho'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Sete Barras'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Severinia'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Silvania'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Silveiras'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Simoes'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Simonsen'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Socorro'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Sodrelia'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Solemar'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Sorocaba'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Sousas'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Sud Mennucci'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Suinana'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Sumare'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Sussui'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Suzanapolis'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Suzano'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Tabajara'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Tabapua'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Tabatinga'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Taboao da Serra'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Taciba'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Taguai'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Taiacu'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Taiacupeba'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Taiuva'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Talhado'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Tambau'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Tanabi'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Tapinas'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Tapirai'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Tapiratiba'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Taquaral'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Taquaritinga'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Taquarituba'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Taquarivai'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Tarabai'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Taruma'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Tatui'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Taubate'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Tecainda'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Tejupa'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Teodoro Sampaio'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Termas de Ibira'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Terra Nova D''oeste'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Terra Roxa'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Tibirica'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Tibirica do Paranapanema'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Tiete'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Timburi'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Toledo'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Torre de Pedra'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Torrinha'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Trabiju'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Tremembe'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Tres Aliancas'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Tres Fronteiras'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Tres Pontes'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Tres Vendas'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Tuiuti'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Tujuguaba'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Tupa'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Tupi'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Tupi Paulista'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Turiba do Sul'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Turiuba'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Turmalina'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Turvinia'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Ubarana'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Ubatuba'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Ubirajara'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Uchoa'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Uniao Paulista'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Universo'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Urania'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Uru'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Urupes'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Ururai'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Utinga'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Vale Formoso'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Valentim Gentil'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Valinhos'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Valparaiso'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Vangloria'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Vargem'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Vargem Grande do Sul'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Vargem Grande Paulista'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Varpa'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Varzea Paulista'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Venda Branca'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Vera Cruz'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Vicente de Carvalho'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Vicentinopolis'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Vila Dirce'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Vila Nery'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Vila Xavier'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Vinhedo'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Viradouro'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Vista Alegre do Alto'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Vitoria Brasil'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Vitoriana'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Votorantim'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Votuporanga'),
       (NEXTVAL('SEQ_CIDADE'), 'SP', 'Zacarias');
